ROCKER = [
    ('Atletyka', 2),
    ('Bijatyka', 6),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 2),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 2),
    ('Perswazja', 6),
    ('Pierwsza pomoc', 6),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 4),
    ('Wykształcenie', 2),
    ('Atrakcyjność', 4),
    ('Broń biała', 6),
    ('Broń krótka', 6),
    ('Gra na instrumencie - Gitara elektryczna', 6),
    ('Komponowanie', 6),
    ('Moda i styl', 4),
    ('Znajomość półświatka', 6),
]

SOLO = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 2),
    ('Odczytywanie emocji', 2),
    ('Percepcja', 6),
    ('Perswazja', 2),
    ('Pierwsza pomoc', 6),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 2),
    ('Broń biała', 6),
    ('Broń długa', 6),
    ('Broń krótka', 6),
    ('Odporność na tortury/narkotyki', 6),
    ('Ogień ciągły', 6),
    ('Przesłuchiwanie', 6),
    ('Taktyka', 6),
]

NETRUNNER = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 2),
    ('Odczytywanie emocji', 2),
    ('Percepcja', 2),
    ('Perswazja', 2),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 6),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 6),
    ('Broń krótka', 6),
    ('Cyberinżynieria', 6),
    ('Elektronika i zabezpieczenia', 6),
    ('Kryptografia', 6),
    ('Podstawowe naprawy', 6),
    ('Przeszukiwanie baz danych', 6),
    ('Ukrycie/Znalezienie przedmiotu', 6),
]

TECH = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 2),
    ('Odczytywanie emocji', 2),
    ('Percepcja', 2),
    ('Perswazja', 2),
    ('Pierwsza pomoc', 6),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 6),
    ('Broń długa', 6),
    ('Cyberinżynieria', 6),
    ('Elektronika i zabezpieczenia', 6),
    ('Naprawa broni', 6),
    ('Naprawa pojazdów lądowych', 6),
    ('Nauka - Fizyka', 6),
    ('Podstawowe naprawy', 6),
]

MEDIC = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 6),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 2),
    ('Perswazja', 2),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 6),
    ('Broń długa', 6),
    ('Cyberinżynieria', 4),
    ('Dedukcja', 6),
    ('Nauka - Biologia', 6),
    ('Odporność na tortury/narkotyki', 4),
    ('Podstawowe naprawy', 6),
    ('Ratownictwo medyczne', 6),
]

MEDIA = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 6),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 6),
    ('Perswazja', 6),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 6),
    ('Wykształcenie', 2),
    ('Broń krótka', 6),
    ('Czytanie z ruchu warg', 4),
    ('Dedukcja', 6),
    ('Fotografia/Film', 4),
    ('Komponowanie', 6),
    ('Przekupstwo', 6),
    ('Przeszukiwanie baz danych', 4),
]

COP = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 6),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 2),
    ('Perswazja', 6),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 6),
    ('Broń długa', 6),
    ('Broń krótka', 6),
    ('Dedukcja', 6),
    ('Kryminologia', 6),
    ('Ogień ciągły', 6),
    ('Przesłuchiwanie', 6),
    ('Tropienie', 6),
]

CORP = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 6),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 2),
    ('Perswazja', 6),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 6),
    ('Atrakcyjność', 6),
    ('Biurokracja', 6),
    ('Broń krótka', 6),
    ('Czytanie z ruchu warg', 6),
    ('Dedukcja', 6),
    ('Księgowość', 6),
    ('Robienie interesów', 4),
]

FIXER = [
    ('Atletyka', 2),
    ('Bijatyka', 2),
    ('Język - Slang uliczny', 4),
    ('Koncentracja', 2),
    ('Konwersacja', 6),
    ('Odczytywanie emocji', 6),
    ('Percepcja', 2),
    ('Perswazja', 4),
    ('Pierwsza pomoc', 2),
    ('Skradanie się', 2),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 6),
    ('Wykształcenie', 2),
    ('Broń krótka', 6),
    ('Fałszerstwo', 6),
    ('Handel', 6),
    ('Otwieranie zamków', 4),
    ('Przekupstwo', 6),
    ('Robienie interesów', 6),
    ('Znajomość półświatka', 6),
]

NOMAD = [
    ('Atletyka', 2),
    ('Bijatyka', 6),
    ('Język - Slang uliczny', 2),
    ('Koncentracja', 2),
    ('Konwersacja', 2),
    ('Odczytywanie emocji', 2),
    ('Percepcja', 4),
    ('Perswazja', 2),
    ('Pierwsza pomoc', 6),
    ('Skradanie się', 6),
    ('Unik', 6),
    ('Wiedza lokalna - Twoja okolica', 2),
    ('Wykształcenie', 2),
    ('Broń biała', 6),
    ('Broń krótka', 6),
    ('Handel', 6),
    ('Opieka nad zwierzętami', 6),
    ('Prowadzenie pojazdów', 6),
    ('Sztuka przetrwania', 6),
    ('Tropienie', 6),
]

SKILLS = {
    'rocker': ROCKER,
    'solo': SOLO,
    'netrunner': NETRUNNER,
    'tech': TECH,
    'medic': MEDIC,
    'media': MEDIA,
    'cop': COP,
    'corp': CORP,
    'fixer': FIXER,
    'nomad': NOMAD
}

def get_skills(role):
    """
    Returns the skills for the given role.
    """
    return SKILLS[role]