"""empty message

Revision ID: 5ed2461d266b
Revises: 
Create Date: 2025-05-13 23:17:27.322578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed2461d266b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('int', sa.Integer(), nullable=False),
    sa.Column('ref', sa.Integer(), nullable=False),
    sa.Column('dex', sa.Integer(), nullable=False),
    sa.Column('tech', sa.Integer(), nullable=False),
    sa.Column('cool', sa.Integer(), nullable=False),
    sa.Column('will', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('move', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('emp_base', sa.Integer(), nullable=False),
    sa.Column('humanity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('special_ability', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('inherit', sa.String(length=50), nullable=False),
    sa.Column('cost_multiplier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_skills')
    op.drop_table('character_roles')
    op.drop_table('skills')
    op.drop_table('role')
    op.drop_table('character')
    # ### end Alembic commands ###
