"""empty message

Revision ID: 73b611819c4f
Revises: 8a29c8def4d8
Create Date: 2025-05-17 23:05:51.089360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b611819c4f'
down_revision = '8a29c8def4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('health',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('health',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
