"""empty message

Revision ID: 772352faa55e
Revises: cf2de3289998
Create Date: 2025-06-26 22:34:45.362782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772352faa55e'
down_revision = 'cf2de3289998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account_entries', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
